### ISSUE TITLE
Door sides don't invert when ATC changes direction

### ISSUE THREAD

**Issue by gbl08ma** [orwell96/advtrains#27]
I have noticed that when the player manually reverses the direction of the train, the side controlled by each door button also changes, so A always controls the doors on the right hand side of the train when it's facing the direction of movement. This makes sense.

In theory this would allow one to always use the same ATC code on all the ATC rails that correspond to a station, without needing to know whether the train is going "forwards" or "backwards". In my map (where trains ride on the left side, "British way"), that would mean that the OL command would always be used.

But apparently, when the train direction is reversed by a ATC rail (even if the player is riding the train), then the OL command will open the doors on the "wrong" side.
I believe this is a bug; if this is intended behavior, then I suggest changing it to work like I said, because otherwise one needs to use conditionals on the ATC rails to use either OL or OR depending on the direction of the train (and even that will not work right all the time, because the train may be in "reverse" but it may have been reversed by a player and in that case, the doors will be reversed - a big mess).

I'm not sure I explained the problem well enough, so if you're confused here's a relatively long video where I reproduce the problem: https://tny.im/dl/door_bug.mp4
I forgot to show but the ATC rail at the end of the track, which reverses the direction, has the command: `I+ B0 W R D10 S8;` . The rails I didn't show just slow down the train.

**Comment by orwell96** [comment]
The door opening side is not dependent of train moving direction, but only relative to the direction the arrows on the atc rail are pointing.
When looking in arrow direction OL will open the left doors and OR the right ones, independent of if the train is driving towards you or away from you
I couldn't watch the video yet

**Comment by gbl08ma** [comment]
Apparently the problem is that right now, the arrows in the ATC rails are pointing the wrong direction. If it looks into that then I'm sure that once I rotate them, things will start working properly.

However, I'm relatively sure I placed them with the arrows always pointing towards the expected direction of movement. This may explain why things worked well the first few times after I placed the ATC rails. But now they are no longer pointing in the right direction. Something must have changed their orientation since then, which is strange. I'll rotate them again and see whether things break again.

After several hours during which everything worked right, now I have trains unexpectedly stopping in the middle of the tracks. And it's not even on the ATC rails where they are supposed to stop and open the doors. I believe it may have to do with world loading/unloading, so I'll get trains moving again and see whether they stop again without ever stopping the server.

**Comment by orwell96** [comment]
If problems occur, try to right-click the ATC rail and click Save again, in some cases this can fix problems.
I recognized wrong behavior some time ago at a single station of my subway network (one out of ~80 ATC rails) once, but couldn't reproduce it since then.

**Comment by orwell96** [comment]
Maybe you send me your map so I can look what's wrong, if you want.

**Comment by orwell96** [comment]
The reason why some ATC rails may have suddenly changed direction could be the node database, there was an issue that rail rotations were not updated when rotated with track worker. It should be fixed.

**Comment by gbl08ma** [comment]
I'm having some trouble getting the automated line to work again because in the queue of trains that lined up behind the one that unexpectedly stopped, two of the trains are "inside" each other and thus neither will move because they collide with the other one. Which means that I'll need to destroy these two and build new ones.
My world is under 100 MB but it depends on quite a lot of mods, including some that I haven't updated for a while and some custom ones, I need to clean this up because otherwise no one can open this world.

Back on topic... I have rotated the ATC rails but somehow, the doors still open on the wrong side - even though the arrows are still pointing towards the right direction.

EDIT: If, on one of the ATC rails I just rotated, I open it and click "Save", then the train will open the doors on the correct side when it gets to that rail.

**Comment by orwell96** [comment]
You can always move one of the trains in one direction, try out. Or couple a train to the end of another and pull it out this way. Collision is only checked at the front of moving trains.
Seems like I need to try to reproduce it myself.

**Comment by gbl08ma** [comment]
It was hard to select each train (each with six wagons) because they were only half a block apart, but I think I managed to get into both and neither would move in either direction. Unfortunately I already deleted both or I would send you to see. I thought it was easily reproducible and you were already aware of it, as it has happened to me a couple of times.

**Comment by orwell96** [comment]
I am tracing down why trains suddenly stop.
I think this issue can be closed since that problem is fixed.

**Comment by gbl08ma** [comment]
Yes, it was more or less my mistake all along. Although I'm still convinced the ATC rails rotated by themselves... anyway, it didn't happen again. You should probably also fix the bug where one must re-save ATC rails for them to assume the new rotation, once rotated.

**Comment by gpcf** [comment]
Reopen this. This problem is not solved, See the subway Lines 2 and 3 on the Linuxworks server, they also tend to get stuck.

**Comment by gbl08ma** [comment]
That's a subject for another issue

**Comment by orwell96** [comment]
Getting stuck is now another issue. You told me the door sides are fixed, and I didn't experience problems either.

**Comment by ValkyrieStella** [comment]
i dont think they are fixed, unless you fixed them as of 2 days ago
